mqtt:
  broker_host: "localhost"
  broker_port: 1883

robot_defaults:
  manufacturer: "RobotCompany"
  interface_name: "uagv"
  protocol_version: "v2"
  max_speed: 0.5
  rotation_speed: 0.7
  battery:
    initial_charge: 30.0
    discharge_rate: 0.01
    charge_rate: 5.0           # %/s, 충전 속도 (30%→80% = 10초)

robots:
  - serial_number: "AGV_001"
    initial_position: { x: 8, y: -10.8, theta: 0.0, map_id: "L1" }
  - serial_number: "AGV_002"
    initial_position: { x: 7.0, y: -2.12, theta: 0.0, map_id: "L1" }
  # - serial_number: "AGV_003"
  # initial_position: { x: 12, y: -10.8, theta: 0.0, map_id: "L1" }

publishing:
  state_interval: 0.5
  visualization_interval: 1.0
  simulation_tick: 0.05
