mqtt:
  broker_host: "localhost"
  broker_port: 1883

robot_defaults:
  manufacturer: "RobotCompany"
  interface_name: "uagv"
  protocol_version: "v2"
  max_speed: 0.5
  rotation_speed: 0.7
  battery:
    initial_charge: 30.0
    discharge_rate: 0.01
    charge_rate: 5.0           # %/s, 충전 속도 (30%→80% = 10초)

robots:
  - serial_number: "AGV_001"
    initial_position: { x: 8, y: -10.8, theta: 0.0, map_id: "L1" }
  - serial_number: "AGV_002"
    initial_position: { x: 18.8, y: -7, theta: 0.0, map_id: "L1" }
  # - serial_number: "AGV_003"
  # initial_position: { x: 12, y: -10.8, theta: 0.0, map_id: "L1" }

download_map:
  map_id: "L1"
  map_download_url: "http://example.com/map.tar.gz"
  map_version: "2.4.1"

action_results:
  pick: "FINISHED"           # FINISHED or FAILED
  drop: "FINISHED"
  startCharging: "FINISHED"
  stopCharging: "FINISHED"
  initPosition: "FINISHED"
  finePositioning: "FINISHED"
  startPause: "FINISHED"
  stopPause: "FINISHED"
  cancelOrder: "FINISHED"
  factsheetRequest: "FINISHED"
  downloadMap: "FINISHED"

publishing:
  state_interval: 0.5
  visualization_interval: 1.0
  simulation_tick: 0.05
